# Generated by Django 4.2.7 on 2024-01-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userManagement", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="Account_status",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
