# Generated by Django 4.2.7 on 2024-02-08 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0003_alter_client_parent_data"),
        ("userManagement", "0007_alter_account_client_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="parent_role",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_id",
                to="company.parent",
            ),
        ),
    ]
