# Generated by Django 4.2.7 on 2024-02-11 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0005_alter_client_state_alter_parent_state"),
        ("userManagement", "0008_alter_account_parent_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="client_role",
            field=models.ForeignKey(
                default=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_data",
                to="company.client",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="parent_role",
            field=models.ForeignKey(
                default=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_id",
                to="company.parent",
            ),
        ),
    ]
