# Generated by Django 4.2.7 on 2024-01-04 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Parent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parent", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parent_company", models.CharField(default="", max_length=200)),
                ("client", models.CharField(max_length=200)),
                ("country", models.CharField(max_length=100)),
                (
                    "parent_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="company.parent"
                    ),
                ),
            ],
        ),
    ]
