# Generated by Django 4.2.7 on 2024-02-08 15:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="parent_company",
        ),
    ]
