# Generated by Django 4.2.7 on 2024-02-08 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_remove_client_parent_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="parent_data",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_info",
                to="company.parent",
            ),
        ),
    ]
