# Generated by Django 4.2.7 on 2024-02-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0003_alter_client_parent_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="state",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="parent",
            name="state",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
