# Generated by Django 4.2.7 on 2024-02-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0004_client_state_parent_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="state",
            field=models.CharField(default="Active", max_length=15),
        ),
        migrations.AlterField(
            model_name="parent",
            name="state",
            field=models.CharField(default="Active", max_length=15),
        ),
    ]
